site_name: EBMeDS 2.0
pages:
  - Home: index.md
  - Installation:
    - System requirements: system-requirements.md
    - Components: components.md
    - Installation: installation.md
  - FHIR:
    - Getting started: api/fhir/getting-started.md
    - CDS hooks: api/fhir/cds-hooks.md
    - Hook catalog: api/fhir/hook-catalog.md
    - Custom REST: api/fhir/custom-rest.md
    - Resources: api/fhir/resources.md
    - Code Systems: api/fhir/code-systems.md
    - Extensions: api/fhir/extensions.md
    - ODA-specific information: api/fhir/oda.md
  - XML:
    - Getting started: api/xml/getting-started.md
    - XML schema: api/xml/xml-schema.md
  - Security & Error handling: security.md
  # - API:
  #   - FHIR STU3: api/fhir-stu3.md
  #   - XML: api/xml.md
theme:
  name: null
  custom_dir: 'cinder'
